# Generated by Django 4.0.4 on 2022-05-13 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_auto_20220513_2151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['position']},
        ),
        migrations.AlterField(
            model_name='photo',
            name='position',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Позиция'),
        ),
    ]
