# Generated by Django 4.0.4 on 2022-05-15 10:18

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_alter_photo_options_alter_photo_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['position'], 'verbose_name': 'фотогафия', 'verbose_name_plural': 'фотографии'},
        ),
        migrations.AlterField(
            model_name='place',
            name='long_description',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Подробное описание'),
        ),
    ]
